services:
    server:
      build: 
        context: ./
      environment:
        NODE_ENV: development
      volumes:
        - ./:/app
      ports:
        - 5050:5050
      env_file: 
        - ./.env